// Typed access to videos/<slug>/data/scenes.json (generated by scripts/build-scenes.mjs).
// "@video" is an alias for the selected video folder (VIDEO env var, see remotion.config.ts).
// All `at` / `start` / `end` times are ABSOLUTE seconds on the voiceover timeline;
// every scene and cue also carries its resolved frame.
import raw from "@video/data/scenes.json";
import type { CtaConfig } from "./components/Cta";

export type LonLat = [number, number];

/** A runbook cue (@"word") resolved against the transcript. */
export type Cue = { word: string; action: string; t: number; frame: number; matched: string; exact: boolean };

export type YearKey = { at: number; value: number };

/** Camera on a still: zoom `scale` centred on image point (x, y), both 0..1 of the image. */
export type Cam = { scale: number; x: number; y: number };

/** Paints a flat color below image row `y` (0..1), for images whose art stops short of the frame. */
export type Matte = { y: number; color: string; colorBottom?: string };

export type KenBurnsConfig = { from: Cam; to: Cam; matte?: Matte; desaturate?: [number, number] };

export type Effects = {
  dust?: number;
  smoke?: number;
  fire?: number;
  rain?: number;
  lightning?: number[]; // absolute seconds of lightning flashes
  vignette?: number; // extra dark vignette
};

export type TextLabel = { text: string; at: number; style: "title" | "name" };

export type SpriteConfig = {
  src: string;
  start: number;
  end: number;
  height: number;
  bottom: number; // px from the bottom edge
  from: number; // x of the sprite's left edge in % of frame width
  to: number;
  bob?: number; // px of vertical bounce per stride
  strideHz?: number;
};

export type TerritoryLayer = { territory: string; fill: string; opacity?: number; outline?: number };
export type MapState = { at: number; duration?: number; mode?: "grow" | "fade"; origin?: LonLat; layers: TerritoryLayer[] };
export type CameraKey = { at: number; center: LonLat; zoom: number };
export type MarkerConfig = {
  id: string;
  label?: string;
  lonlat: LonLat;
  at: number;
  kind?: "city" | "dot";
  pulse?: boolean;
  crossAt?: number;
  flashAt?: number;
  battleAt?: number;
  labelSide?: "top" | "bottom" | "right" | "left";
};
export type LineConfig = {
  id: string;
  path: LonLat[];
  at: number;
  duration?: number;
  style: "river" | "arrow" | "route" | "trade" | "divider";
  smooth?: boolean;
  dots?: { at: number; count: number; period: number; loop?: boolean }; // caravans moving along the line
};
export type RegionLabel = { text: string; lonlat: LonLat; at: number; size?: number; tone?: "light" | "dark"; hideAt?: number };

export type MapSpec = {
  id: string;
  meridian?: number; // central meridian for this map (keeps north up); defaults to the global one
  camera: CameraKey[];
  states: MapState[];
  markers?: MarkerConfig[];
  lines?: LineConfig[];
  regionLabels?: RegionLabel[];
  seaLabels?: { text: string; lonlat: LonLat; size?: number }[];
};

export type DecimalStep = { at: number; value: number; unit: string };

type SceneBase = {
  id: string;
  part: string;
  start: number;
  end: number;
  startFrame: number;
  endFrame: number;
  assets: string[];
  motion: string;
  vo: string;
  cues: Cue[];
  effects?: Effects;
  year?: YearKey[];
  yearEra?: string;
  date?: { text: string; at: number };
  titles?: TextLabel[];
  cta?: CtaConfig; // subscribe overlay, rendered on top of everything (see Video.tsx)
};

export type ImageScene = SceneBase & { type: "image"; image: string; kenBurns: KenBurnsConfig };
export type ParallaxScene = SceneBase & {
  type: "parallax";
  background: { src: string } & KenBurnsConfig;
  sprites: SpriteConfig[];
};
export type MapScene = SceneBase & { type: "map"; map: MapSpec };
export type GfxScene = SceneBase & { type: "gfx"; gfx: "decimal-army"; steps: DecimalStep[] };
/** One shot inside a multi-shot scene: an image with its own camera move, or a map. Starts at `at` (absolute s). */
export type Shot = { at: number; image?: string; kenBurns?: KenBurnsConfig; map?: MapSpec; effects?: Effects };
export type ShotsScene = SceneBase & { type: "shots"; shots: Shot[]; shotFade?: number };
export type Scene = ImageScene | ParallaxScene | MapScene | GfxScene | ShotsScene;

export type MapSettings = {
  extent: [LonLat, LonLat];
  rotate: [number, number];
  parallels: [number, number];
};

export type VideoConfig = {
  meta: {
    id: string;
    title: string;
    fps: number;
    width: number;
    height: number;
    duration: number;
    durationInFrames: number;
    audio: string;
    voiceEnd: number;
    transitionFrames: number;
    fadeOut: { start: number; end: number };
  };
  overlay: { dust: number; parchment: number; grain: number; vignette: number };
  map: MapSettings;
  scenes: Scene[];
};

export const config = raw as unknown as VideoConfig;

/** Absolute seconds -> absolute frame. */
export const sec = (s: number, fps = config.meta.fps) => Math.round(s * fps);

/**
 * Frame window each scene occupies. A scene starts `transitionFrames` early so it can
 * crossfade in over the previous one; the cut point itself stays on the VO boundary.
 */
export const sceneWindow = (index: number) => {
  const { scenes, meta } = config;
  const s = scenes[index];
  const half = Math.round(meta.transitionFrames / 2);
  const from = Math.max(0, s.startFrame - (index > 0 ? half : 0));
  const to = Math.min(meta.durationInFrames, s.endFrame + (index < scenes.length - 1 ? half : 0));
  return { from, durationInFrames: to - from };
};
